{
    "related_post": {
        "ts": "2020-04-22T08:58:12.540000",
        "user": "Maiella",
        "text": "```Traceback (most recent call last): File E:/test.py line 7 in <module> os.rename(src + \\'\\\\\\\\\\ + file dest + \\'\\\\\\\\\\ + file)PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: \\'E:\\\\\\\\test\\\\\\\\dest\\ > \\'E:\\\\\\\\test\\\\\\\\dest\\\\\\\\dest\\'```",
        "conversation_id": "1071",
        "index": 24
    },
    "so_post": {
        "ts": "2020-04-22T09:02:35.694000",
        "user": "Kenzii",
        "text": "@Awsm https://stackoverflow.com/questions/27215462/permissionerrorwinerror32theprocesscannotaccessthefilebecauseitis",
        "conversation_id": "1071",
        "index": 46
    },
    "category": "Direct Solution Provided by Non-Asker",
    "comments": "User had permission issues and the Kenzii provided a link.",
    "meta": {
        "start_date": "2020-04-01T00:02:12.875000",
        "end_time": null,
        "channel_name": "python-general",
        "team_domain": "Python",
        "count": 76489
    }
}